#ifndef EXIT_STATUS_H
# define EXIT_STATUS_H

# define EXIT_STATUS_USAGE	1
# define EXIT_STATUS_MEMORY 2
# define EXIT_STATUS_IO 3
# define EXIT_STATUS_UNEXPECTED_ERROR 4
# define EXIT_STATUS_PARSING_HEADER 5
# define EXIT_STATUS_PARSING_INSTR 6
# define EXIT_STATUS_COMPILE_INSTR 7

#endif
